jQuery.fn.sisFiltro=function(tipoCampo){var conteiner=$(this).attr("id");var clique=true;var t;if($("#hiddent_"+conteiner).val()=="")$("#hiddent_"+conteiner).val(tipoCampo);$("#"+conteiner+" #fil_ini").click(function(){if(clique==true)$("#"+conteiner+" #tudo").show()});$("#FormFiltro #"+conteiner).hover(function(){clearTimeout(t)},function(){t=setTimeout(function(){$("#FormFiltro #"+conteiner+" #tudo").hide()},500)});$("#FormFiltro #"+conteiner+" #tudo li").click(function(){clique=false;$("#FormFiltro #"+
conteiner+" #tudo").hide();sisMontaFiltro(conteiner,this);setTimeout(function(){clique=true},0.1)});$("#FormFiltro #"+conteiner+" #tudo li").hover(function(){$(this).addClass("fundo_fil")},function(){$(this).removeClass("fundo_fil")});function getOpcoesFiltro(tipoCampo){if(tipoCampo=="Float"||tipoCampo=="Inteiro"||tipoCampo=="Data")return'<ul id="fil_ini"><li>=</li></ul><ul id="tudo" style="display:none"><li>=</li><li><></li><li>></li><li><</li><li>>=</li><li><=</li></ul>';else if(tipoCampo=="Texto"||
tipoCampo=="Suggest")return'<ul id="fil_ini"><li>=</li></ul><ul id="tudo" style="display:none"><li>=</li><li><></li><li>*</li><li>A*</li><li>*A</li></ul>';else if(tipoCampo=="CPF"||tipoCampo=="CNPJ"||tipoCampo=="CEP")return'<ul id="fil_ini"><li>=</li></ul><ul id="tudo" style="display:none"><li>=</li><li><></li></ul>';else if(tipoCampo=="Select")return'<ul id="fil_ini"><li>=</li></ul><ul id="tudo" style="display:none"><li>=</li><li><></li></ul>';else return'<ul id="fil_ini"><li>=</li></ul><ul id="tudo" style="display:none"><li>=</li><li><></li></ul>'}
function sisMontaFiltro(conteiner,obj){var selecao=$.trim($(obj).text());$("#FormFiltro #hidden_"+conteiner).val(selecao);$("#FormFiltro #"+conteiner+" #fil_ini li").text(selecao);if(selecao=="E"||selecao=="OU"){var campo=conteiner.substring(11,conteiner.length);var identifica=$("#hiddeni_"+conteiner).val();var cpA=$("#FormFiltro #"+campo).clone();var cpB=$("#FormFiltro #"+campo).clone();$("#FormFiltro #"+conteiner).css("display","none");$("#FormFiltro #"+campo).attr("disabled","disabled");cpA.attr("id",
campo+"A").attr("name",campo+"A");cpB.attr("id",campo+"B").attr("name",campo+"B").val("");var idCloneCampos=$("#FormFiltro #cloneCampos").attr("id");if(idCloneCampos!="cloneCampos")$("<div id='cloneCampos'></div>").prependTo("#FormFiltro");var conteudoA='<div id="sis_filtro_'+campo+'A" class="s_filtro" style="z-index:'+50+'; width:25px; float:left;">'+getOpcoesFiltro(tipoCampo)+"</div>";var conteudoB='<div id="sis_filtro_'+campo+'B" class="s_filtro" style="z-index:'+51+'; width:25px; float:left;">'+
getOpcoesFiltro(tipoCampo)+"</div>";var $divClone=$("<div class='cloneCPs'></div>");$divClone.append("<h1 id='nomeCampos' style='float:left;'> "+identifica+": </h1>");$divClone.append(conteudoA);$divClone.append('<div id="CPA" style="float:left; width:150px; overflow:hidden;"></div>');$divClone.find("#CPA").append(cpA);$divClone.append("<h1 id='CPspan' style='float:left; color:#FF0000;'> "+selecao+" </h1>");$divClone.append("<h1 id='nomeCampos' style='float:left;'> "+identifica+": </h1>");$divClone.append(conteudoB);
$divClone.append('<div id="CPB" style="float:left"></div>');$divClone.find("#CPB").append(cpB);$divClone.append("<h1 id='CPDel' style='float:left;'><a href='#' onClick='removeSisFiltro(this,\""+campo+"\")'><img src='"+URLBASE+"figuras/del_2.gif' border='0' /> Remover este filtro</a></h1> <br clear=\"all\" />");$divClone.append('<input name="hidden_sis_filtro_'+campo+'A" id="hidden_sis_filtro_'+campo+'A" type="hidden" value="="/>');$divClone.append('<input name="hidden_sis_filtro_'+campo+'B" id="hidden_sis_filtro_'+
campo+'B" type="hidden" value="="/>');$("#FormFiltro #cloneCampos").append($divClone);if(tipoCampo=="Float"){$("#FormFiltro #sis_filtro_"+campo+"A").livequery(function(){$(this).sisFiltro(tipoCampo)});$("#FormFiltro #sis_filtro_"+campo+"B").livequery(function(){$(this).sisFiltro(tipoCampo)});$("#FormFiltro #"+campo+"A").livequery(function(){$(this).floatValue()});$("#FormFiltro #"+campo+"B").livequery(function(){$(this).floatValue()})}else if(tipoCampo=="Inteiro"){$("#FormFiltro #sis_filtro_"+campo+
"A").livequery(function(){$(this).sisFiltro(tipoCampo)});$("#FormFiltro #sis_filtro_"+campo+"B").livequery(function(){$(this).sisFiltro(tipoCampo)});$("#FormFiltro #"+campo+"A").livequery(function(){$(this).validation({type:"int"})});$("#FormFiltro #"+campo+"B").livequery(function(){$(this).validation({type:"int"})})}else if(tipoCampo=="Data"){$("#FormFiltro #sis_filtro_"+campo+"A").livequery(function(){$(this).sisFiltro(tipoCampo)});$("#FormFiltro #sis_filtro_"+campo+"B").livequery(function(){$(this).sisFiltro(tipoCampo)});
$("#FormFiltro #"+campo+"A").livequery(function(){$(this).calendar().mask("99/99/9999")});$("#FormFiltro #"+campo+"B").livequery(function(){$(this).calendar().mask("99/99/9999")})}else if(tipoCampo=="Texto"){$("#FormFiltro #FormFiltro #sis_filtro_"+campo+"A").livequery(function(){$(this).sisFiltro(tipoCampo)});$("#FormFiltro #sis_filtro_"+campo+"B").livequery(function(){$(this).sisFiltro(tipoCampo)})}else if(tipoCampo=="CPF"){$("#FormFiltro #sis_filtro_"+campo+"A").livequery(function(){$(this).sisFiltro(tipoCampo)});
$("#FormFiltro #sis_filtro_"+campo+"B").livequery(function(){$(this).sisFiltro(tipoCampo)});$("#FormFiltro #"+campo+"A").livequery(function(){$(this).mask("999.999.999-99")});$("#FormFiltro #"+campo+"B").livequery(function(){$(this).mask("999.999.999-99")})}else if(tipoCampo=="CNPJ"){$("#FormFiltro #sis_filtro_"+campo+"A").livequery(function(){$(this).sisFiltro(tipoCampo)});$("#FormFiltro #"+campo+"A").livequery(function(){$(this).mask("99.999.999/9999-99")})}else if(tipoCampo=="CEP"){$("#FormFiltro #sis_filtro_"+
campo+"A").livequery(function(){$(this).sisFiltro(tipoCampo)});$("#FormFiltro #"+campo+"A").livequery(function(){$(this).mask("99999-999")})}else{$("#FormFiltro #sis_filtro_"+campo+"A").livequery(function(){$(this).sisFiltro(tipoCampo)});$("#FormFiltro #sis_filtro_"+campo+"B").livequery(function(){$(this).sisFiltro(tipoCampo)})}}}};
function removeSisFiltro(obj,nomeCampo){$(obj).parent().parent().find(":input").each(function(){$("#FormFiltro #"+$(this).attr("id")).expire()});$(obj).parent().parent().remove();var conteudoCloneCampos=$("#FormFiltro #cloneCampos").html();$("#FormFiltro #sis_filtro_"+nomeCampo).show();$("#FormFiltro #sis_filtro_"+nomeCampo+" #fil_ini li").text("=");$("#FormFiltro #hidden_sis_filtro_"+nomeCampo).val("=");$("#FormFiltro #"+nomeCampo).attr("disabled",false);if(conteudoCloneCampos=="")$("#FormFiltro #cloneCampos").remove()}
;